import content into instruqt

diff --git a/instruqt-tracks/o11y-as-code-pulumi/03-tags/check-docker-vm b/instruqt-tracks/o11y-as-code-pulumi/03-tags/check-docker-vm
--- a/instruqt-tracks/o11y-as-code-pulumi/03-tags/check-docker-vm
+++ b/instruqt-tracks/o11y-as-code-pulumi/03-tags/check-docker-vm
@@ -1,12 +1,14 @@
 #!/bin/bash
 set -euxo pipefail
 
-if [ ! -d /newrelic/o11y/node_modules ]; then
-    fail-message "dependencies not installed. Did you run npm install?"
+# Check if the tags exists on the apps
+
+if ! grep "team" /o11y/index.ts; then
+    fail-message "Couldn't find the team tag. Did you use tags?"
     exit 1
 fi
 
-if [ ! -f /newrelic/o11y/Pulumi.dev.yaml ]; then
-    fail-message "Couldn't find the dev stack. Did you run pulumi config?"
+if ! grep "env" /o11y/index.ts; then
+    fail-message "Couldn't find the team tag. Did you use tags?"
     exit 1
 fi
diff --git a/instruqt-tracks/o11y-as-code-pulumi/04-dashboards/check-docker-vm b/instruqt-tracks/o11y-as-code-pulumi/04-dashboards/check-docker-vm
--- a/instruqt-tracks/o11y-as-code-pulumi/04-dashboards/check-docker-vm
+++ b/instruqt-tracks/o11y-as-code-pulumi/04-dashboards/check-docker-vm
@@ -1,12 +1,7 @@
 #!/bin/bash
 set -euxo pipefail
 
-if [ ! -d /newrelic/o11y/node_modules ]; then
-    fail-message "dependencies not installed. Did you run npm install?"
-    exit 1
-fi
-
-if [ ! -f /newrelic/o11y/Pulumi.dev.yaml ]; then
-    fail-message "Couldn't find the dev stack. Did you run pulumi config?"
+if ! grep "dashboard" /o11y/index.ts; then
+    fail-message "Couldn't find the dashboard output. Did you use dashboards?"
     exit 1
 fi
